/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.vbgn.gradle.buildaspects;

import be.vbgn.gradle.buildaspects.project.dsl.BuildAspects;
import be.vbgn.gradle.buildaspects.project.dsl.BuildComponents;
import be.vbgn.gradle.buildaspects.settings.project.ComponentProjectDescriptor;
import java.util.List;
import java.util.stream.Collectors;
import org.gradle.api.Plugin;
import org.gradle.api.initialization.Settings;
import org.gradle.api.internal.plugins.DslObject;

public class BuildAspectsPlugin implements Plugin<Settings> {

    @Override
    public void apply(Settings settings) {
        BuildAspects buildAspects = new DslObject(settings).getExtensions()
                .create("buildAspects", BuildAspects.class, settings);
    }
}
