/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.vbgn.gradle.buildaspects;

import static org.junit.Assert.assertNotNull;

import org.gradle.api.Project;
import org.gradle.api.internal.plugins.PluginApplicationException;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

public class BuildAspectsPluginTest {
    @Test(expected = PluginApplicationException.class)
    public void throwsWhenAppliedOnProject() {
        Project project = ProjectBuilder.builder().build();
        project.getPluginManager().apply(BuildAspectsPlugin.class);
    }

}
