/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.vbgn.gradle.buildaspects;

import static org.junit.Assert.assertNotNull;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

/**
 * A simple unit test for the 'be.vbgn.gradle.buildaspects.greeting' plugin.
 */
public class BuildAspectsPluginTest {

    @Test
    public void pluginRegistersATask() {
    }
}
